### ISSUE TITLE
Menus are not rendered properly if the terminal window is smaller that the menu height

### ISSUE THREAD

**Issue by elliot40404** [charmbracelet/huh#41]
![image](https://github.com/charmbracelet/huh/assets/67360013/f7c19568-409a-4af5-8c09-b9f3dcefb511)
![image](https://github.com/charmbracelet/huh/assets/67360013/23790e65-46a1-4951-9929-72161f0f5393)

I am on windows 11 23H2 using powershell as the shell and windows-terminal as thee terminal emulator with go version 1.21.5

**Comment by maaslalani** [comment]
Hey @elliot40404, this is definitely an issue with longer forms. In the future, we will likely introduce one of two options:

1. Auto-pagination when forms exceed height limits / dimensions.
2. Vertical scrolling of current group as forms are completed.

For now, we would recommend to ensure the form groups aren't too long so that short terminals don't render them incorrectly.

**Comment by maaslalani** [comment]
Hi @elliot40404, thanks again for creating this issue. I'm happy to let you know that we introduced vertical scrolling for long form groups. Let me know if that solves the issue for you!

* https://github.com/charmbracelet/huh/pull/95

**Comment by elliot40404** [comment]
Thank you very much. I will give it a try.
